services:
  db_ttr:
    image: pgvector/pgvector:pg17
    container_name: ttr-pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgvector
    ports:
      - "5051:5432"
    volumes:
      - pgdata_ttr:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  ollama_ttr:
    image: ollama/ollama:0.5.5
    container_name: ttr-ollama-service
    ports:
      - "11435:11434"
    volumes:
      - ollama_data_ttr:/root/.ollama

volumes:
  pgdata_ttr:
  ollama_data_ttr:
